### ISSUE TITLE
Segmentation fault on ARM

### ISSUE THREAD

**Issue by ecarver** [wilseypa/warped#7]
The segfault occurs only when simulating in parallel. Running with valgrind or within gdb also ameliorates the problem. Information from a core dump of the epidemic model is given below.

```
(0)root@odroid0#./epidemicSim -c parallel.json --simulate epidemic/LargeEPIDEMIC.xml                                                                                                                          /root/thesis/warped-models/src
Initializing simulation...
zsh: segmentation fault (core dumped)  ./epidemicSim -c parallel.json --simulate epidemic/LargeEPIDEMIC.xml
(139)root@odroid0#gdb epidemicSim core                                                                                                                                                                        /root/thesis/warped-models/src
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/thesis/warped-models/src/epidemicSim...done.
[New LWP 21318]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `./epidemicSim -c parallel.json --simulate epidemic/LargeEPIDEMIC.xml'.
Program terminated with signal 11, Segmentation fault.
#0  0x4029bb18 in TimeWarpSimulationManager::~TimeWarpSimulationManager (this=0x2abe8, __vtt_parm=0x402df96c, __in_chrg=<optimized out>) at TimeWarpSimulationManager.cpp:98
98          if (myDVFSManager) {delete myDVFSManager;}
(gdb) bt
#0  0x4029bb18 in TimeWarpSimulationManager::~TimeWarpSimulationManager (this=0x2abe8, __vtt_parm=0x402df96c, __in_chrg=<optimized out>) at TimeWarpSimulationManager.cpp:98
#1  0x402bb942 in ThreadedTimeWarpSimulationManager::ThreadedTimeWarpSimulationManager (this=0x2abe8, numberOfWorkerThreads=<optimized out>, syncMechanism=..., loadBalancing=<optimized out>, loadBalancingMetric=...,
    loadBalancingTrigger=..., loadBalancingVarianceThresh=0.20000000000000001, loadBalancingNormalInterval=3, loadBalancingNormalThresh=5, loadBalancingRelaxedInterval=15, loadBalancingRelaxedThresh=2, scheduleQScheme=...,
    causalityType=..., scheduleQCount=2, initApplication=0x27ae8, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at ThreadedTimeWarpSimulationManager.cpp:90
#2  0x4029e77c in TimeWarpSimulationManagerFactory::allocate (this=<optimized out>, configuration=..., parent=0x27ae8) at TimeWarpSimulationManagerFactory.cpp:67
#3  0x40292d44 in TimeWarpConfigurationManager::configure (this=0x27ca8, configuration=...) at TimeWarpConfigurationManager.cpp:46
#4  0x40285d56 in Simulation::configure (this=0x27cd0, configuration=...) at Simulation.cpp:48
#5  0x40285f84 in Simulation::instance (configuration=0xbeff8378, userApplication=<optimized out>) at Simulation.cpp:25
#6  0x402a130e in WarpedMain::initializeSimulation (this=0xbeff8520) at WarpedMain.cpp:79
#7  0x4025463c in WarpedMain::main (this=0xbeff8520, argc=<optimized out>, argv=<optimized out>) at WarpedMain.cpp:115
#8  0x0000c53e in main (argc=5, argv=0xbeff8784) at epidemic/EpidemicMain.cpp:54
(gdb)
```

**Comment by ecarver** [comment]
This particular segfault is fixed by commit 5eff6bcf1586d697100dbac1839c648e939b8657
